#!/usr/bin/env bash
#Install nginx on my remote server

sudo apt-get update && sudo apt -y upgrade
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
