#!/usr/bin/env bash
# displays numbers from 1 to 100,
# a) FizzBuzz when number is multiple of both 3 and 5,
# b) Fizz when number is multiple of only 3,
# c) Buzz when number is multiple of only 5
COUNTER=1
while [ $COUNTER -lt 101 ]
do
    if [ $((COUNTER%35)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((COUNTER%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((COUNTER%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$COUNTER"
    fi
    let COUNTER+=1
done
