#!/usr/bin/env bash
# displays numbers from 1 to 100,
# a) FizzBuzz when number is multiple of both 3 and 5,
# b) Fizz when number is multiple of only 3,
# c) Buzz when number is multiple of only 5
i=1
for (( i=1; i <= 100; i++ )); do
    if [[ $((i % 15)) == 0 ]]; then
        echo "FizzBuzz"
        elif [[ $(( i % 5 )) == 0 ]]; then
        echo "Buzz"
        elif [[ $(( i % 3 )) == 0 ]];  then
        echo "Fizz"
    else
        echo "$i"
    fi
done
