#!/usr/bin/env bash
# displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.
cont=0
while [ $cont -lt 10 ];
do
    if [ $cont -eq 9 ]
    then
echo "Hi"
    fi
    echo "Holberton School"
    ((cont=cont+1))
done
