#!/usr/bin/env bash
# Loops from 1 to 10 and: 
# a) displays bad luck for the 4th loop iteration
# b)displays good luck for the 8th loop iteration
# c)displays 'Best School" for the other iterations
COUNTER=0
while [ $COUNTER -lt 10 ];
do
    if [ $COUNTER -eq 3 ]
    then
echo "bad luck"
    elif [ $COUNTER -eq 7 ]
    then
echo "good luck"
    else
echo "Best School"
    fi
    let COUNTER=COUNTER+1
done
