#!/bin/bash
COUNTER=0
while [ $COUNTER -lt 10 ];
do
    if [ $COUNTER -eq 3 ]
    then
echo "bad luck"
    elif [ $COUNTER -eq 7 ]
    then
echo "good luck"
    else
echo "Holberton School"
    fi
    let COUNTER=COUNTER+1
done
