#!/usr/bin/bash env
# displays numbers from 1 to 20 and: a) displays 4 and then bad luck from China for the 4th loop iteration, b) displays 9 and then bad luck from Japan for the 9th loop iteration, c) displays 17 and then bad luck from Italy for the 17th loop iteration.
Counter=1
while [ "$Counter" -le 20 ];
    do
    echo "$Counter"
    case "$Counter" in
4)
    echo 4 "bad luck from China"
    ;;
9)
    echo 9 "bad luck from Japan"
    ;;
17)
    echo 17 "bad luck from Italy"
    ;;
    esac
    let Counter=Counter+1
done
