#!/usr/bin/env bash
# displays: a) The content of the current directory b) in a list format c) Where only the part of the name after the first dash is displayed
for i in *
do
    echo "$i" | rev | cut -d "-" -f 1 | rev
done
