#!/usr/bin/env bash
# Bash script to "install and configure HAproxy on my lb-01 server"

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8\*

echo "
frontend http
 bind *:80
 stats uri /haproxy?stats
 default_backend web-backend
backend web-backend
balance roundrobin
server 3452-web-01 	174.129.153.137 check
server 3452-web-02  34.227.229.55 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
