#!/usr/bin/env bash
# Installs load balancer HAproxy

# updates and upgrades the webserver
sudo apt-get -y update
sudo apt-get -y upgrade

# installs HAproxy
sudo apt-get -y install haproxy

# creates instructions for addition to config file
inst="frontend http_web
\n\tbind *:80
\n\tstats uri /haproxy?stats
\n\tdefault_backend custom_backend
\nbackend custom_backend
\n\tbalance roundrobin
\n\tserver web-01 174.129.153.137:80 check
\n\tserver web-02 34.227.229.55:80 check"

# echo instructions for the config file
echo -e "$inst" | sudo tee -a /etc/haproxy/haproxy.cfg

# checks validity of config file
sudo haproxy -f /etc/haproxy/haproxy.cfg -c

# restart haproxy
sudo service haproxy restart
